local P=game:GetService("Players");local pl=P.LocalPlayer;local U=game:GetService("UserInputService");local S=game:GetService("StarterGui");local R=game:GetService("RunService")
local s=Instance.new("ScreenGui");s.Name="CoolkidGui";s.Parent=pl.PlayerGui;s.ResetOnSpawn=false
local f=Instance.new("Frame");f.Size=UDim2.new(0,300,0,200);f.Position=UDim2.new(0.5,-150,0.5,-100);f.BackgroundColor3=Color3.fromRGB(0,0,0);f.BorderSizePixel=2;f.BorderColor3=Color3.fromRGB(255,0,0);f.Parent=s
local st=Instance.new("UIStroke");st.Thickness=2;st.Color=Color3.fromRGB(255,0,0);st.Parent=f
local t=Instance.new("TextLabel");t.Size=UDim2.new(1,0,0,50);t.BackgroundTransparency=1;t.Text="Martinetti's Scripts :)";t.TextColor3=Color3.fromRGB(255,255,255);t.TextStrokeColor3=Color3.fromRGB(255,0,0);t.TextStrokeTransparency=0;t.Font=Enum.Font.Code;t.TextSize=24;t.Parent=f
local ti=Instance.new("TextLabel");ti.Size=UDim2.new(0,100,0,20);ti.Position=UDim2.new(0.85,-100,0.9,0);ti.BackgroundTransparency=1;ti.Text="Tiktok: m4rt1n3tt1";ti.TextColor3=Color3.fromRGB(255,255,255);ti.TextStrokeColor3=Color3.fromRGB(255,0,0);ti.TextStrokeTransparency=0;ti.Font=Enum.Font.Code;ti.TextSize=12;ti.Parent=f
local b=Instance.new("TextBox");b.Size=UDim2.new(0.8,0,0,30);b.Position=UDim2.new(0.1,0,0.3,0);b.BackgroundColor3=Color3.fromRGB(0,0,0);b.TextColor3=Color3.fromRGB(255,255,255);b.PlaceholderText="Enter h4ck code...";b.PlaceholderColor3=Color3.fromRGB(255,0,0);b.Font=Enum.Font.Code;b.TextSize=18;b.Parent=f
local bs=Instance.new("UIStroke");bs.Thickness=1;bs.Color=Color3.fromRGB(255,0,0);bs.Parent=b
local m=Instance.new("TextButton");m.Size=UDim2.new(0,20,0,20);m.Position=UDim2.new(0.95,-20,0,0);m.BackgroundTransparency=1;m.Text="_";m.TextColor3=Color3.fromRGB(255,255,255);m.TextStrokeColor3=Color3.fromRGB(255,0,0);m.TextStrokeTransparency=0;m.Font=Enum.Font.Code;m.TextSize=16;m.Parent=f
local mi=false;m.MouseButton1Click:Connect(function()mi=not mi;b.Visible=ti.Visible=not mi;f.Size=mi and UDim2.new(0,300,0,50)or UDim2.new(0,300,0,200)end)
local h=false;local p=false;local e=false;local ef=Instance.new("Folder");ef.Name="ESP";ef.Parent=game.CoreGui;local ow=pl.Character and pl.Character.Humanoid.WalkSpeed or 16;local oj=pl.Character and pl.Character.Humanoid.JumpPower or 50;local ij=nil
local function ti(e)if ij then ij:Disconnect();ij=nil end;if e and pl.Character then ij=U.JumpRequest:Connect(function()if pl.Character and pl.Character.Humanoid then pl.Character.Humanoid:ChangeState(Enum.HumanoidStateType.Jumping)end end)end end
local function te(e)e=e;for _,c in pairs(ef:GetChildren())do c:Destroy()end;if e then for _,p in pairs(P:GetPlayers())do if p~=pl and p.Character and p.Character:FindFirstChild("Head")and p.Character:FindFirstChild("HumanoidRootPart")then local h=Instance.new("Highlight");h.Parent=ef;h.Adornee=p.Character;h.FillColor=Color3.fromRGB(255,0,0);h.OutlineColor=Color3.fromRGB(255,0,0);h.FillTransparency=0.5;h.OutlineTransparency=0;local bg=Instance.new("BillboardGui");bg.Parent=ef;bg.Adornee=p.Character.Head;bg.Size=UDim2.new(0,200,0,50);bg.StudsOffset=Vector3.new(0,2,0);bg.AlwaysOnTop=true;local nl=Instance.new("TextLabel");nl.Parent=bg;nl.Size=UDim2.new(1,0,0.5,0);nl.BackgroundTransparency=1;nl.Text=p.Name;nl.TextColor3=Color3.fromRGB(255,0,0);nl.TextStrokeTransparency=0;nl.TextStrokeColor3=Color3.fromRGB(0,0,0);nl.Font=Enum.Font.Code;nl.TextSize=18;local dl=Instance.new("TextLabel");dl.Parent=bg;dl.Size=UDim2.new(1,0,0.5,0);dl.Position=UDim2.new(0,0,0.5,0);dl.BackgroundTransparency=1;dl.TextColor3=Color3.fromRGB(255,0,0);dl.TextStrokeTransparency=0;dl.TextStrokeColor3=Color3.fromRGB(0,0,0);dl.Font=Enum.Font.Code;dl.TextSize=14;local c; c=R.Heartbeat:Connect(function()if p.Character and p.Character:FindFirstChild("HumanoidRootPart")and pl.Character and pl.Character:FindFirstChild("HumanoidRootPart")then local d=math.floor((p.Character.HumanoidRootPart.Position-pl.Character.HumanoidRootPart.Position).Magnitude);dl.Text=d.." studs"else c:Disconnect()end end)end end end end
local function sp(e)p=e;local pc=Color3.fromRGB(255,105,180);if e then f.BackgroundColor3=pc;f.BorderColor3=pc;st.Color=pc;t.Text="Te amo Anabella :3";t.TextColor3=pc;t.TextStrokeColor3=Color3.fromRGB(255,255,255);ti.TextColor3=pc;ti.TextStrokeColor3=Color3.fromRGB(255,255,255);b.BackgroundColor3=pc;b.TextColor3=Color3.fromRGB(255,255,255);b.PlaceholderColor3=Color3.fromRGB(255,255,255);bs.Color=pc;m.TextColor3=pc;m.TextStrokeColor3=Color3.fromRGB(255,255,255)else f.BackgroundColor3=Color3.fromRGB(0,0,0);f.BorderColor3=Color3.fromRGB(255,0,0);st.Color=Color3.fromRGB(255,0,0);t.Text="Martinetti's Scripts :)";t.TextColor3=Color3.fromRGB(255,255,255);t.TextStrokeColor3=Color3.fromRGB(255,0,0);ti.TextColor3=Color3.fromRGB(255,255,255);ti.TextStrokeColor3=Color3.fromRGB(255,0,0);b.BackgroundColor3=Color3.fromRGB(0,0,0);b.TextColor3=Color3.fromRGB(255,255,255);b.PlaceholderColor3=Color3.fromRGB(255,0,0);bs.Color=Color3.fromRGB(255,0,0);m.TextColor3=Color3.fromRGB(255,255,255);m.TextStrokeColor3=Color3.fromRGB(255,0,0)end end
b.FocusLost:Connect(function(ep)if ep then local i=b.Text;local li=i:lower();if i=="ESP"then te(true);b.Text="";S:SetCore("SendNotification",{Title="Esp highlight activado!",Text="Disfruta :)",Duration=3})elseif i=="UNESP"and e then te(false);b.Text="";S:SetCore("SendNotification",{Title="Esp highlight desactivado",Text="Chau esp pipipi",Duration=3})elseif li=="martinetti"and not h then h=true;if pl.Character and pl.Character.Humanoid then pl.Character.Humanoid.WalkSpeed=20;pl.Character.Humanoid.JumpPower=50;ti(true)end;b.Text="";S:SetCore("SendNotification",{Title="H4CK activado :)",Text="20 speed + infjump",Duration=3})elseif li=="desactivar hack"and h then h=false;if pl.Character and pl.Character.Humanoid then pl.Character.Humanoid.WalkSpeed=ow;pl.Character.Humanoid.JumpPower=oj;ti(false);sp(false)end;b.Text="";S:SetCore("SendNotification",{Title="H4CK DEACTIVATED",Text="Hack desactivated :( 16 speed + no infjump",Duration=3})elseif li=="gui kawai"then sp(true);b.Text="";S:SetCore("SendNotification",{Title="Te sientes muy onichan?",Text="GUI en rosa activado xd",Duration=3})elseif li=="gui normal"then sp(false);b.Text="";S:SetCore("SendNotification",{Title="GUI normal activada",Text="Pongase serio siervo",Duration=3})else b.Text="";S:SetCore("SendNotification",{Title="ERROR",Text="Invalid h4ck code!",Duration=3})end end end)
P.PlayerAdded:Connect(function(p)if e then p.CharacterAdded:Connect(function()wait(1);te(false);te(true)end)end)
local d,di,ds,sp;f.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then d=true;ds=i.Position;sp=f.Position;i.Changed:Connect(function()if i.UserInputState==Enum.UserInputState.End then d=false end end)end end);f.InputChanged:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseMovement or i.UserInputType==Enum.UserInputType.Touch then di=i end end);U.InputChanged:Connect(function(i)if i==di and d then local d=i.Position-ds;f.Position=UDim2.new(sp.X.Scale,sp.X.Offset+d.X,sp.Y.Scale,sp.Y.Offset+d.Y)end end)
pl.CharacterAdded:Connect(function(c)ow=c.Humanoid.WalkSpeed;oj=c.Humanoid.JumpPower end)
